language: java
install: skip

os: macosx

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew jar
  - jdk_switcher use oraclejdk8
  - export JAVA_HOME=$HOME/oraclejdk8
  - ./gradlew jar2pkg

matrix:
  include:
    - script:
        - ./gradlew build
        - ./gradlew jar
        jdk: oraclejdk11
    - script:
        - jdk_switcher use oraclejdk8
        - export JAVA_HOME=$HOME/oraclejdk8
        - ./gradlew jar2pkg
        jdk: oraclejdk8